# Generated by Django 4.2.8 on 2024-03-02 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='chat', chained_model_field='chat', on_delete=django.db.models.deletion.CASCADE, related_name='messages', show_all=True, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message.chat', verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.ManyToManyField(blank=True, to='message.file', verbose_name='Прикреплённые файлы'),
        ),
        migrations.AddField(
            model_name='message',
            name='unread_users',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='chat', chained_model_field='chat', to=settings.AUTH_USER_MODEL, verbose_name='Непрочитавшие пользователи'),
        ),
        migrations.AddField(
            model_name='file',
            name='added_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавивший пользователь'),
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
