# Generated by Django 4.2.8 on 2024-03-06 12:55

import django.core.validators
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='slug',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/123/Desktop/backend_chat/media'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'txt', 'xlsx', 'pdf', 'jpg', 'png'])], verbose_name='Прикреплённые файлы'),
        ),
    ]
