# Generated by Django 4.2.8 on 2024-03-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_remove_file_slug_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
    ]
