# Generated by Django 4.2.8 on 2024-02-22 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0004_remove_message_is_read_isreadmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isreadmessage',
            name='user_is_read',
        ),
        migrations.AddField(
            model_name='isreadmessage',
            name='users_is_read',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Прочитавшие пользователи'),
        ),
        migrations.AlterField(
            model_name='isreadmessage',
            name='is_read',
            field=models.BooleanField(default=True, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='isreadmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_read_messages', to='message.message', verbose_name='Сообщение'),
        ),
    ]
