# Generated by Django 4.2.8 on 2024-02-22 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_remove_isreadmessage_user_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='isreadmessage',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='message.chat', verbose_name='Чат'),
        ),
    ]
