# Generated by Django 4.2.8 on 2024-02-23 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0010_alter_message_unread_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='unread_users',
            field=models.ManyToManyField(default=1, related_name='unread_messages', to=settings.AUTH_USER_MODEL, verbose_name='Непрочитавшие пользователи'),
        ),
    ]
