# Generated by Django 4.2.8 on 2024-02-24 10:47

from django.conf import settings
from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0012_alter_message_unread_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='unread_users',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='chat', chained_model_field='chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
