# Generated by Django 4.2.8 on 2024-02-24 11:12

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0013_alter_message_unread_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='chat', chained_model_field='chat', on_delete=django.db.models.deletion.CASCADE, related_name='messages', show_all=True, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='unread_users',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='chat', chained_model_field='chat', to=settings.AUTH_USER_MODEL, verbose_name='Непрочитавшие пользователи'),
        ),
    ]
