# Generated by Django 4.2.8 on 2024-02-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_alter_message_author_alter_message_unread_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Прикреплённые файлы'),
        ),
    ]
