# Generated by Django 4.2.8 on 2024-02-29 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0017_remove_message_files_file_message_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'txt', 'xlsx', 'pdf', 'jpg', 'png'])], verbose_name='Прикреплённые файлы'),
        ),
        migrations.AlterField(
            model_name='message',
            name='files',
            field=models.ManyToManyField(blank=True, to='message.file', verbose_name='Прикреплённые файлы'),
        ),
    ]
